# Generated by Django 3.2.7 on 2022-09-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0004_rename_ref_if_order_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='price_currency',
        ),
    ]
