version: "3.8"

services:
  app:
    build: ./app
    container_name: app
    restart: always
    volumes:
      - static_volume:/app/shopping_app/staticfiles
      - media_volume:/app/shopping_app/media
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shop
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - postgres_volumes:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/shopping_app/staticfiles
      - media_volume:/app/shopping_app/media
    depends_on:
      - app

volumes:
  # postgres_volumes:
  static_volume:
  media_volume:
