# Generated by Django 3.2.7 on 2021-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=20, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیر فعال')),
                ('product', models.ManyToManyField(blank=True, to='product.Product')),
            ],
            options={
                'verbose_name': 'تگ/برچسب',
                'verbose_name_plural': 'تگ/برچسب',
            },
        ),
    ]
