# Generated by Django 3.2.7 on 2023-05-23 11:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=50, verbose_name='نام فروشگاه')),
                ('english_name', models.CharField(max_length=50, verbose_name='نام فروشگاه به انگلیسی')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='تلفن همراه')),
                ('landline', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='تلفن ثابت')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('address', models.TextField(max_length=100, verbose_name='آدرس فروشگاه')),
                ('domain', models.URLField(blank=True, null=True, verbose_name='دامنه سایت')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'اطلاعات فروشگاه اینترنتی',
                'verbose_name_plural': 'اطلاعات فروشگاه اینترنتی',
            },
        ),
    ]
