# Generated by Django 3.2.7 on 2021-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AlterField(
            model_name='mattress',
            name='image',
            field=models.ImageField(upload_to='mattress', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', verbose_name='عکس'),
        ),
    ]
