# Generated by Django 3.2.7 on 2022-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220920_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=10000000, max_digits=11, verbose_name='قیمت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='تعداد فروخته شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='تخفیف'),
        ),
    ]
