# Generated by Django 3.2.7 on 2023-05-01 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220920_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت موجودی')),
            ],
            options={
                'verbose_name': 'طرح محصول',
                'verbose_name_plural': 'طرح های محصول',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mattress',
        ),
        migrations.AddField(
            model_name='category',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='آیا دسته بندی اصلی می باشد؟'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mattress',
        ),
        migrations.AddField(
            model_name='design',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='product',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.design', verbose_name='طرح محصول'),
            preserve_default=False,
        ),
    ]
