# Generated by Django 3.2.7 on 2022-09-14 11:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20211017_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=60, unique=True, verbose_name='آدرس')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت موجودی')),
                ('category_type', models.CharField(choices=[('S', 'تاب'), ('M', 'مدل'), ('T', 'بافت')], max_length=1, verbose_name='نوع دسته بندی')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='دیدگاه')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='امتیاز')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'گالری محصول', 'verbose_name_plural': 'گالری محصولات'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='product',
            name='texture',
        ),
        migrations.AddField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0, verbose_name='تعداد فروخته شده'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='product title', max_length=60, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='body_color',
        ),
        migrations.AddField(
            model_name='product',
            name='body_color',
            field=models.ManyToManyField(to='product.Color', verbose_name='رنگ بدنه'),
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.DeleteModel(
            name='Texture',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='product.Category', verbose_name='دسته بندی'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'product')},
        ),
    ]
