# Generated by Django 3.2.7 on 2022-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20220918_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_sold',
            field=models.IntegerField(default=0, editable=False, verbose_name='تعداد فروخته شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, editable=False, to='product.IPAdrees', verbose_name='بازدید'),
        ),
    ]
