# Generated by Django 3.2.7 on 2022-09-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220918_1255'),
        ('product_order', '0002_order_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.useraddress', verbose_name='آدرس'),
        ),
    ]
