# Generated by Django 3.2.7 on 2022-09-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0003_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref_if',
            new_name='ref_id',
        ),
    ]
