# Generated by Django 3.2.7 on 2022-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0005_auto_20220920_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1000000, max_digits=11, verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
