# Generated by Django 3.2.7 on 2021-09-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=100, verbose_name='موضوع')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_checked', models.BooleanField(default=False, verbose_name='چک شده')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباطات با ما',
            },
        ),
    ]
